
import type { Region } from "../types/Region";
export const stateProvinceNames: Record<Region, string[]> = {
		AA: [],
		AC: [],
		AD: [],
		AE: [],
		AF: [],
		AG: ["Saint George", "Saint John", "Saint Mary", "Saint Paul", "Saint Peter", "Saint Philip"],
		AI: [],
		AL: [],
		AM: [],
		AO: [],
		AQ: [],
		AR: [],
		AS: [],
		AT: [],
		AU: ["New South Wales", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia", "Australian Capital Territory", "Northern Territory"],
		AW: [],
		AX: [],
		AZ: [],
		BA: [],
		BB: ["Christ Church", "Saint Andrew", "Saint George", "Saint James", "Saint John", "Saint Joseph", "Saint Lucy", "Saint Michael", "Saint Peter", "Saint Philip", "Saint Thomas"],
		BD: [],
		BE: [],
		BF: [],
		BG: [],
		BH: [],
		BI: [],
		BJ: [],
		BL: [],
		BM: ["Devonshire", "Hamilton", "Paget", "Pembroke", "Sandys", "Smith's", "Southampton", "St. George's", "Warwick"],
		BN: [],
		BO: [],
		BQ: [],
		BR: [],
		BS: ["Acklins", "Berry Islands", "Bimini", "Cat Island", "Crooked Island", "Eleuthera", "Exuma", "Grand Bahama", "Inagua", "Long Island", "Mayaguana", "New Providence", "Ragged Island", "Rum Cay", "San Salvador"],
		BT: [],
		BV: [],
		BW: [],
		BY: [],
		BZ: ["Belize", "Cayo", "Corozal", "Orange Walk", "Stann Creek", "Toledo"],
		CA: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"],
		CC: [],
		CD: [],
		CF: [],
		CG: [],
		CH: [],
		CI: [],
		CK: [],
		CL: [],
		CM: [],
		CN: [],
		CO: [],
		CR: [],
		CU: [],
		CV: [],
		CW: [],
		CX: [],
		CY: [],
		CZ: [],
		DE: [],
		DJ: [],
		DK: [],
		DM: ["Saint Andrew", "Saint David", "Saint George", "Saint John", "Saint Joseph", "Saint Luke", "Saint Mark", "Saint Patrick", "Saint Paul", "Saint Peter"],
		DO: [],
		DZ: [],
		EC: [],
		EE: [],
		EG: [],
		EH: [],
		ER: [],
		ES: [],
		ET: [],
		EU: [],
		EZ: [],
		FI: [],
		FJ: [],
		FK: [],
		FM: [],
		FO: [],
		FR: [],
		GA: [],
		GB: ["England", "Northern Ireland", "Scotland", "Wales"],
		GD: ["Saint Andrew", "Saint David", "Saint George", "Saint John", "Saint Mark", "Saint Patrick"],
		GE: [],
		GF: [],
		GG: [],
		GH: [],
		GI: [],
		GL: [],
		GM: [],
		GN: [],
		GP: [],
		GQ: [],
		GR: [],
		GS: [],
		GT: [],
		GU: [],
		GW: [],
		GY: ["Barima-Waini", "Cuyuni-Mazaruni", "Demerara-Mahaica", "East Berbice-Corentyne", "Essequibo Islands-West Demerara", "Mahaica-Berbice", "Pomeroon-Supenaam", "Potaro-Siparuni", "Upper Demerara-Berbice", "Upper Takutu-Upper Essequibo"],
		HK: [],
		HM: [],
		HN: [],
		HR: [],
		HT: [],
		HU: [],
		IC: [],
		ID: [],
		IE: ["Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"],
		IL: [],
		IM: [],
		IN: [],
		IO: [],
		IQ: [],
		IR: [],
		IS: [],
		IT: [],
		JE: [],
		JM: ["Clarendon", "Hanover", "Kingston", "Manchester", "Portland", "Saint Andrew", "Saint Ann", "Saint Catherine", "Saint Elizabeth", "Saint James", "Saint Mary", "Saint Thomas", "Trelawny", "Westmoreland"],
		JO: [],
		JP: [],
		KE: [],
		KG: [],
		KH: [],
		KI: [],
		KM: [],
		KN: ["Christ Church Nichola Town", "Saint Anne Sandy Point", "Saint George Basseterre", "Saint George Gingerland", "Saint James Windward", "Saint John Capisterre", "Saint John Figtree", "Saint Mary Cayon", "Saint Paul Capisterre", "Saint Paul Charlestown", "Saint Peter Basseterre", "Saint Thomas Lowland", "Saint Thomas Middle Island", "Trinity Palmetto Point"],
		KP: [],
		KR: [],
		KW: [],
		KY: ["Bodden Town", "East End", "George Town", "North Side", "Sister Islands", "West Bay"],
		KZ: [],
		LA: [],
		LB: [],
		LC: ["Anse la Raye", "Castries", "Choiseul", "Dennery", "Gros Islet", "Laborie", "Micoud", "Soufrière", "Vieux Fort"],
		LI: [],
		LK: [],
		LR: [],
		LS: [],
		LT: [],
		LU: [],
		LV: [],
		LY: [],
		MA: [],
		MC: [],
		MD: [],
		ME: [],
		MF: [],
		MG: [],
		MH: [],
		MK: [],
		ML: [],
		MM: [],
		MN: [],
		MO: [],
		MP: [],
		MQ: [],
		MR: [],
		MS: ["Saint Anthony", "Saint Georges"],
		MT: [],
		MU: [],
		MV: [],
		MW: [],
		MX: [],
		MY: [],
		MZ: [],
		NA: [],
		NC: [],
		NE: [],
		NF: [],
		NG: [],
		NI: [],
		NL: [],
		NO: [],
		NP: [],
		NR: [],
		NU: [],
		NZ: ["Auckland", "Bay of Plenty", "Canterbury", "Gisborne", "Hawke's Bay", "Manawatu-Wanganui", "Marlborough", "Nelson", "Northland", "Otago", "Southland", "Taranaki", "Tasman", "Waikato", "Wellington", "West Coast"],
		OM: [],
		PA: [],
		PE: [],
		PF: [],
		PG: [],
		PH: [],
		PK: [],
		PL: [],
		PM: [],
		PN: [],
		PR: [],
		PS: [],
		PT: [],
		PW: [],
		PY: [],
		QA: [],
		RE: [],
		RO: [],
		RS: [],
		RU: [],
		RW: [],
		SA: [],
		SB: [],
		SC: [],
		SD: [],
		SE: [],
		SG: [],
		SH: [],
		SI: [],
		SJ: [],
		SK: [],
		SL: [],
		SM: [],
		SN: [],
		SO: [],
		SR: [],
		SS: [],
		ST: [],
		SU: [],
		SV: [],
		SX: [],
		SY: [],
		SZ: [],
		TA: [],
		TC: ["Grand Turk", "Salt Cay", "South Caicos", "East Caicos", "Middle Caicos", "North Caicos", "Providenciales", "West Caicos"],
		TD: [],
		TF: [],
		TG: [],
		TH: [],
		TJ: [],
		TK: [],
		TL: [],
		TM: [],
		TN: [],
		TO: [],
		TR: [],
		TT: ["Couva-Tabaquite-Talparo", "Diego Martin", "Eastern Tobago", "Penal-Debe", "Point Fortin", "Port of Spain", "Princes Town", "San Fernando", "San Juan-Laventille", "Sangre Grande", "Siparia", "Tunapuna-Piarco", "Western Tobago"],
		TV: [],
		TZ: [],
		UA: [],
		UG: [],
		UM: [],
		US: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "American Samoa", "Guam", "Northern Mariana Islands", "Puerto Rico", "U.S. Virgin Islands", "Armed Forces Americas (AA)", "Armed Forces Europe (AE)", "Armed Forces Pacific (AP)"],
		UY: [],
		UZ: [],
		VA: [],
		VC: ["Charlotte", "Grenadines", "Saint Andrew", "Saint David", "Saint George", "Saint Patrick"],
		VE: [],
		VG: ["Anegada", "Jost Van Dyke", "Tortola", "Virgin Gorda"],
		VI: ["Saint Croix", "Saint John", "Saint Thomas"],
		VN: [],
		VU: [],
		WF: [],
		WS: ["A'ana", "Aiga-i-le-Tai", "Atua", "Fa'asaleleaga", "Gaga'emauga", "Gaga'ifomauga", "Palauli", "Satupa'itea", "Tuamasaga", "Va'a-o-Fonoti", "Vaisigano"],
		XK: [],
		YE: [],
		YT: [],
		ZA: ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "North West", "Northern Cape", "Western Cape"],
		ZM: [],
		ZW: []
};
